#!/usr/bin/env python3
"""Build widget/yu-home-element.js from index.html.

Converts the standalone homepage into a light-DOM Web Component (<yu-home>)
that renders inline in a Wix page (SEO-friendly, like BerlinWalk's widgets on
GitHub Pages). All CSS is scoped under the `yu-home` tag so nothing leaks into
Wix. The enquiry form posts to the Vercel enquiry API (absolute URL).
"""
import json
import re
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
SRC = ROOT / "index.html"
OUT = ROOT / "widget" / "yu-home-element.js"
API_URL = "https://yusufucuz-com.vercel.app/api/enquiry"
PAGES_BASE = "https://fenerszymanski.github.io/yusufucuz.com/"
FONTS = ("https://fonts.googleapis.com/css2?family=Newsreader:ital,opsz,wght@0,6..72,400;"
         "0,6..72,500;0,6..72,600;1,6..72,400;1,6..72,500&family=Work+Sans:wght@400;500;600&display=swap")


def prefix_selectors(selector_list, scope):
    out = []
    for sel in selector_list.split(","):
        s = sel.strip()
        if not s:
            continue
        if s in (":root", "html", "body"):
            out.append(scope)
        elif s.startswith(scope):
            out.append(s)
        else:
            out.append(f"{scope} {s}")
    return ", ".join(out)


def scope_css(css, scope):
    out = []
    i, n = 0, len(css)
    while i < n:
        j = css.find("{", i)
        if j == -1:
            out.append(css[i:])
            break
        prelude = css[i:j].strip()
        depth, k = 1, j + 1
        while k < n and depth > 0:
            if css[k] == "{":
                depth += 1
            elif css[k] == "}":
                depth -= 1
            k += 1
        body = css[j + 1:k - 1]
        if prelude.startswith("@"):
            if prelude.startswith("@media") or prelude.startswith("@supports"):
                out.append(prelude + "{" + scope_css(body, scope) + "}")
            else:  # @keyframes, @font-face, etc. — leave inner untouched
                out.append(prelude + "{" + body + "}")
        else:
            out.append(prefix_selectors(prelude, scope) + "{" + body + "}")
        i = k
    return "".join(out)


def main():
    html = SRC.read_text()
    css = re.search(r"<style>(.*?)</style>", html, re.S).group(1)
    # Strip comments first: the scoper would otherwise treat a comment as part
    # of the next selector and produce `yu-home /* ... */ .foo`, which is invalid.
    css = re.sub(r"/\*.*?\*/", "", css, flags=re.S)
    scoped = scope_css(css, "yu-home").strip()

    body = re.search(r"<body>(.*?)<script>", html, re.S).group(1).strip()
    # Absolutize asset URLs so images load when embedded cross-origin in Wix.
    body = body.replace('src="assets/', f'src="{PAGES_BASE}assets/')

    css_js = json.dumps(scoped)
    markup_js = json.dumps(body)

    js = f"""// AUTO-GENERATED by scripts/build-widget.py from index.html. Do not edit by hand.
// <yu-home> — the yusufucuz.com homepage as a light-DOM Web Component,
// embedded into the Wix site (SEO-friendly inline DOM). Rebuild after editing
// index.html:  python3 scripts/build-widget.py
(() => {{
  const CSS = {css_js};
  const MARKUP = {markup_js};
  const API_URL = {json.dumps(API_URL)};
  const FONTS = {json.dumps(FONTS)};

  class YuHome extends HTMLElement {{
    connectedCallback() {{
      if (this.__rendered) return;
      this.__rendered = true;
      if (!document.getElementById('yu-fonts')) {{
        const l = document.createElement('link');
        l.id = 'yu-fonts'; l.rel = 'stylesheet'; l.href = FONTS;
        (document.head || document.documentElement).appendChild(l);
      }}
      this.innerHTML = '<style>' + CSS + '</style>' + MARKUP;
      this._wireNav();
      this._wireForm();
    }}

    _wireNav() {{
      // In-page links are scrolled by hand: inside Wix a bare href="#id" can be
      // swallowed by the host router, AND native scroll-behavior:'smooth' is
      // ignored there (only an instant jump lands). Scoped to this element.
      const root = this;
      const NAV_OFFSET = 92; // sticky header height

      function glide(toY) {{
        const fromY = window.pageYOffset || document.documentElement.scrollTop || 0;
        const dist = toY - fromY;
        if (Math.abs(dist) < 2) {{ window.scrollTo(0, toY); return; }}
        const dur = Math.min(800, Math.max(280, Math.abs(dist) * 0.45));
        const t0 = performance.now();
        (function step(now) {{
          const p = Math.min(1, (now - t0) / dur);
          const e = p < 0.5 ? 2 * p * p : 1 - Math.pow(-2 * p + 2, 2) / 2;
          window.scrollTo(0, Math.round(fromY + dist * e));
          if (p < 1) requestAnimationFrame(step);
        }})(t0);
      }}

      root.addEventListener('click', (e) => {{
        const a = e.target && e.target.closest ? e.target.closest('a[href^="#"]') : null;
        if (!a || !root.contains(a)) return;
        const hash = a.getAttribute('href');
        if (!hash) return;
        if (hash === '#top' || hash === '#') {{ glide(0); e.preventDefault(); return; }}
        const el = root.querySelector(hash);
        if (!el) return;
        const y = el.getBoundingClientRect().top + (window.pageYOffset || 0) - NAV_OFFSET;
        glide(Math.max(0, y));
        e.preventDefault();
      }});
    }}

    _wireForm() {{
      const root = this;
      const form = root.querySelector('#enquiry');
      if (!form) return;
      const btn = root.querySelector('#submitBtn');
      const errEl = root.querySelector('#ferror');
      const okEl = root.querySelector('#fok');
      const fields = form.querySelector('.fform');
      const showError = (m) => {{ errEl.textContent = m; errEl.style.display = 'block'; }};

      form.addEventListener('submit', (e) => {{
        e.preventDefault();
        errEl.style.display = 'none';
        const data = {{
          name: form.name.value.trim(), email: form.email.value.trim(),
          dates: form.dates.value.trim(), group: form.group.value.trim(),
          interests: form.interests.value.trim()
        }};
        if (data.name.length < 2) return showError('Please enter your name.');
        if (!/^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$/.test(data.email)) return showError('Please enter a valid email address.');
        if (data.dates.length < 2) return showError('Please enter at least one preferred date.');
        const g = parseInt(data.group, 10);
        if (!(g >= 1 && g <= 10)) return showError('Please enter a group size from 1 to 10.');

        btn.disabled = true; btn.textContent = 'Sending…';
        fetch(API_URL, {{ method: 'POST', headers: {{ 'Content-Type': 'application/json' }}, body: JSON.stringify(data) }})
          .then((r) => r.json().then((j) => ({{ ok: r.ok, j }})))
          .then((res) => {{
            if (res.ok && res.j && res.j.ok) {{ fields.style.display = 'none'; okEl.style.display = 'block'; }}
            else {{ showError((res.j && res.j.error) || 'Something went wrong. Please email info@yusufucuz.com.'); btn.disabled = false; btn.textContent = 'Send my enquiry'; }}
          }})
          .catch(() => {{
            const b = encodeURIComponent('Name: '+data.name+'\\nEmail: '+data.email+'\\nDates: '+data.dates+'\\nGroup: '+data.group+'\\nInterests: '+data.interests);
            showError('Could not send just now. Email me instead: ');
            errEl.innerHTML += '<a href="mailto:info@yusufucuz.com?subject=Private%20tour%20enquiry&body='+b+'" style="color:#B0782A;text-decoration:underline">info@yusufucuz.com</a>';
            btn.disabled = false; btn.textContent = 'Send my enquiry';
          }});
      }});
    }}
  }}

  if (window.customElements && !customElements.get('yu-home')) {{
    customElements.define('yu-home', YuHome);
  }}
}})();
"""
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(js)
    print(f"wrote {OUT.relative_to(ROOT)} ({round(len(js)/1024)} KB)")


if __name__ == "__main__":
    main()
