#!/usr/bin/env python3
"""Build widget/yu-parts-element.js from the <nav> and <footer> in index.html.

The homepage is a custom element, so the Wix header and footer are the only
chrome the blog pages have — and rebuilding them by hand in Wix would be a
second copy to keep in sync. This emits both as one light-DOM element to drop
into the Wix header and footer sections.

One element, not two, on purpose: Wix mounts every Custom Element widget as
the tag <wix-default-custom-element>, and a tag can only be registered once.
Two scripts would race, and the loser would render the winner's markup. So a
single element ships both fragments and picks by `data-part`, falling back to
where it finds itself in the page.

One source of truth: edit index.html, rerun this, and homepage + blog change
together. In-page links become absolute — from /post/... a bare "#book" means
nothing. Landing on the homepage with a hash is handled by the widget itself
(see _wireNav in build-widget.py).
"""
import importlib.util
import json
import re
import pathlib

HERE = pathlib.Path(__file__).resolve().parent
ROOT = HERE.parent
OUT = ROOT / "widget" / "yu-parts-element.js"
SRC = ROOT / "index.html"
SITE = "https://www.yusufucuz.com"
FONTS = ("https://fonts.googleapis.com/css2?family=Newsreader:ital,opsz,wght@0,6..72,400;"
         "0,6..72,500;0,6..72,600;1,6..72,400;1,6..72,500&family=Work+Sans:wght@400;500;600&display=swap")

# Scope on a wrapper class, not the tag: Wix mounts this as
# <wix-default-custom-element>, so anything keyed to a tag would never match.
SCOPE = ".yu-part"

# The homepage nav is sticky and sits on a divider; inside the Wix header
# section both are already handled. The footer keeps its own sand band so it
# looks the same as the homepage's.
OVERRIDES = """
.yu-part{display:block;width:100%}
.yu-part nav{position:static;border-bottom:0;background:transparent}
.yu-part footer{padding:28px 0}
"""

# The Wix blog renders post bodies through the Ricos viewer, whose paragraphs
# carry no spacing metadata, so they render with margin:0 and every paragraph
# runs straight into the next. Wix exposes no paragraph-spacing control on the
# Blog Post element. This element is already on every blog page (as the header),
# so it injects one global rule that gives the post body real paragraph rhythm.
# Ricos viewer blocks all carry an id that starts with "viewer-" — a long-stable
# convention — and nothing else on the site does, so the selector is safe.
POST_CSS = (
    'p[id^="viewer-"]{margin:0 0 1.3em !important}'
    'h2[id^="viewer-"],h3[id^="viewer-"]{margin:1.7em 0 .5em !important}'
)

_spec = importlib.util.spec_from_file_location("build_widget", HERE / "build-widget.py")
_bw = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(_bw)


def absolutise(markup):
    """Point in-page links at the homepage and asset srcs at GitHub Pages, so
    the footer's BerlinWalk logo loads on the blog pages too (relative
    `assets/...` would 404 there — the images live on Pages, not the Wix site)."""
    markup = markup.replace('href="#top"', 'href="%s/"' % SITE)
    markup = re.sub(r'href="#([\w-]+)"', 'href="%s/#\\1"' % SITE, markup)
    return markup.replace('src="assets/', 'src="%sassets/' % _bw.PAGES_BASE)


TEMPLATE = """// AUTO-GENERATED by scripts/build-parts.py from index.html. Do not edit by hand.
// <yu-part> — the homepage's nav and footer, for the Wix header and footer
// sections so the blog pages carry the same chrome. Rebuild after editing
// index.html:  python3 scripts/build-parts.py
(() => {
  const CSS = __CSS__;
  const PARTS = { nav: __NAV__, footer: __FOOT__ };
  const FONTS = __FONTS__;
  const POST_CSS = __POSTCSS__;

  class YuPart extends HTMLElement {
    connectedCallback() {
      if (this.__rendered) return;
      this.__rendered = true;
      if (!document.getElementById('yu-fonts')) {
        const l = document.createElement('link');
        l.id = 'yu-fonts'; l.rel = 'stylesheet'; l.href = FONTS;
        (document.head || document.documentElement).appendChild(l);
      }
      // Give Ricos post bodies real paragraph spacing (see POST_CSS note).
      if (!document.getElementById('yu-post-typography')) {
        const s = document.createElement('style');
        s.id = 'yu-post-typography'; s.textContent = POST_CSS;
        (document.head || document.documentElement).appendChild(s);
      }
      this.innerHTML = '<style>' + CSS + '</style>'
        + '<div class="yu-part">' + PARTS[this.whichPart()] + '</div>';
    }

    // Explicit wins; otherwise infer from where Wix dropped us. Anything
    // unrecognised renders the nav, which is the safer thing to be wrong about.
    whichPart() {
      const asked = this.getAttribute('data-part');
      if (asked === 'footer' || asked === 'nav') return asked;
      return this.closest('footer, #SITE_FOOTER') ? 'footer' : 'nav';
    }
  }

  if (!window.customElements) return;
  if (!customElements.get('yu-part')) customElements.define('yu-part', YuPart);

  // Wix's Custom Element widget mounts <wix-default-custom-element> and gives
  // no way to rename it, so register under that name too — a subclass, because
  // one class cannot be registered twice.
  if (!customElements.get('wix-default-custom-element')) {
    customElements.define('wix-default-custom-element', class extends YuPart {});
  }
})();
"""


def main():
    html = SRC.read_text()

    css = re.search(r"<style>(.*?)</style>", html, re.S).group(1)
    css = re.sub(r"/\*.*?\*/", "", css, flags=re.S)  # see build-widget.py
    scoped = _bw.scope_css(css, SCOPE).strip() + OVERRIDES

    nav = absolutise(re.search(r"<nav>.*?</nav>", html, re.S).group(0).strip())
    foot = absolutise(re.search(r"<footer>.*?</footer>", html, re.S).group(0).strip())

    js = (TEMPLATE
          .replace("__CSS__", json.dumps(scoped))
          .replace("__POSTCSS__", json.dumps(POST_CSS))
          .replace("__NAV__", json.dumps(nav))
          .replace("__FOOT__", json.dumps(foot))
          .replace("__FONTS__", json.dumps(FONTS)))

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(js)
    print("wrote %s (%d KB)" % (OUT.relative_to(ROOT), round(len(js) / 1024)))


if __name__ == "__main__":
    main()
