#!/usr/bin/env python3
"""Build widget/yu-nav-element.js from the <nav> in index.html.

The homepage is a custom element, so the Wix header only ever shows on the
blog pages — which left them with a bare wordmark and no way through to the
tour. Rather than rebuild that header by hand in Wix (a second thing to keep
in sync, in a place that is awkward to edit), this emits the *same* nav as a
second light-DOM element, <yu-nav>, to drop into the Wix header section.

One source of truth: edit the nav in index.html, rerun this, and both the
homepage and the blog header change together.

The in-page links become absolute, because from /post/... a bare "#book" means
nothing. Landing on the homepage with a hash is handled by the widget itself
(see _wireNav in build-widget.py).
"""
import importlib.util
import json
import re
import pathlib

HERE = pathlib.Path(__file__).resolve().parent
ROOT = HERE.parent

# Reuse the homepage build's CSS scoper. Loaded by path because the filename
# is hyphenated and so cannot be imported as a module name.
_spec = importlib.util.spec_from_file_location("build_widget", HERE / "build-widget.py")
_build_widget = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(_build_widget)
scope_css = _build_widget.scope_css
SRC = ROOT / "index.html"
OUT = ROOT / "widget" / "yu-nav-element.js"
SITE = "https://www.yusufucuz.com"
FONTS = ("https://fonts.googleapis.com/css2?family=Newsreader:ital,opsz,wght@0,6..72,400;"
         "0,6..72,500;0,6..72,600;1,6..72,400;1,6..72,500&family=Work+Sans:wght@400;500;600&display=swap")

# The homepage nav is sticky and rests on a divider. Inside the Wix header
# section both are already handled by Wix, so switch them off here.
OVERRIDES = """
yu-nav{display:block}
yu-nav nav{position:static;border-bottom:0;background:transparent}
"""


def absolutise(markup):
    """Point in-page links at the homepage; leave external ones alone."""
    markup = markup.replace('href="#top"', f'href="{SITE}/"')
    return re.sub(r'href="#([\w-]+)"', rf'href="{SITE}/#\1"', markup)


def main():
    html = SRC.read_text()

    css = re.search(r"<style>(.*?)</style>", html, re.S).group(1)
    css = re.sub(r"/\*.*?\*/", "", css, flags=re.S)  # see build-widget.py
    scoped = scope_css(css, "yu-nav").strip() + OVERRIDES

    markup = absolutise(re.search(r"<nav>.*?</nav>", html, re.S).group(0).strip())

    js = f"""// AUTO-GENERATED by scripts/build-nav.py from the <nav> in index.html.
// Do not edit by hand.
// <yu-nav> — the homepage header, for the Wix header section so the blog
// pages carry the same navigation. Rebuild after editing index.html:
//   python3 scripts/build-nav.py
(() => {{
  const CSS = {json.dumps(scoped)};
  const MARKUP = {json.dumps(markup)};
  const FONTS = {json.dumps(FONTS)};

  class YuNav extends HTMLElement {{
    connectedCallback() {{
      if (this.__rendered) return;
      this.__rendered = true;
      if (!document.getElementById('yu-fonts')) {{
        const l = document.createElement('link');
        l.id = 'yu-fonts'; l.rel = 'stylesheet'; l.href = FONTS;
        (document.head || document.documentElement).appendChild(l);
      }}
      this.innerHTML = '<style>' + CSS + '</style>' + MARKUP;
    }}
  }}

  if (window.customElements && !customElements.get('yu-nav')) {{
    customElements.define('yu-nav', YuNav);
  }}
}})();
"""
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(js)
    print(f"wrote {OUT.relative_to(ROOT)} ({round(len(js)/1024)} KB)")


if __name__ == "__main__":
    main()
